import Head from 'next/head'
import React from 'react'
import { Line, LineChart, ResponsiveContainer, YAxis, XAxis, Tooltip, Legend } from 'recharts';
import axios from 'axios';



export default function Home() {

  const stocks_trigger = typeof document !== 'undefined' && document.querySelector('#stocks-tab');
  const stocks_target = typeof document !== 'undefined' && document.querySelector('#stocks');
  const crypto_trigger = typeof document !== 'undefined' && document.querySelector('#crypto-tab');
  const crypto_target = typeof document !== 'undefined' && document.querySelector('#crypto');

  const data = [
    {
      "name": "Page A",
      "uv": 4000,
      "pv": 2400,
      "amt": 2400
    },
    {
      "name": "Page B",
      "uv": 3000,
      "pv": 1398,
      "amt": 2210
    },
    {
      "name": "Page C",
      "uv": 2000,
      "pv": 9800,
      "amt": 2290
    },
    {
      "name": "Page D",
      "uv": 2780,
      "pv": 3908,
      "amt": 2000
    },
    {
      "name": "Page E",
      "uv": 1890,
      "pv": 4800,
      "amt": 2181
    },
    {
      "name": "Page F",
      "uv": 2390,
      "pv": 3800,
      "amt": 2500
    },
    {
      "name": "Page G",
      "uv": 3490,
      "pv": 4300,
      "amt": 2100
    }
  ]

  const tabElements = [
    {
        id: 'stocks',
        triggerEl: stocks_trigger,
        targetEl: stocks_target
    },
    {
        id: 'crypto',
        triggerEl: crypto_trigger,
        targetEl: crypto_target,
    }
  ];
  

  // const tabs = new Tabs(tabElements);
  // tabs.show('stocks')
  
  
  return  (
    <div className="bg-grey h-screen w-screen">
      <Head>
        <title>If only</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class="flex flex-col items-center"> {/* Main Column */}
          <div className="bg-white w-3/4 h-3/4 rounded shadow-lg m-10"> {/* Paper */}
            
            <div className="text-sm font-poppins font-medium text-center text-black" border-b border-gray-200> {/* Selection tab */}
              <ul className="flex flex-wrap -mb-px"  data-tabs-toggle="#input-tab">
                <li class="mr-2">
                  <button class="inline-block p-4 rounded-t-lg border-b-2" id="stocks-tab" data-tabs-target="#stocks" type="button" role="tab" aria-controls="stocks" aria-selected="true">Stocks</button>
                </li>
                <li class="mr-2">
                  <button class="inline-block p-4 rounded-t-lg border-b-2" id="crypto-tab" data-tabs-target="#crypto" type="button" role="tab" aria-controls="crypto" aria-selected="true">Crypto</button>
                </li>
              </ul>
            </div>

            <div id="input-tab">
              <div className="hidden p-4" id="stocks" role="tabpanel" aria-labelledby="stocks-tab" data-tabs-toggle="#stock-tab"> {/* Stocks input*/}
                  <h1>stocks</h1>
                  <h1>stocks</h1>
                  <h1>stocks</h1>
                  <h1>stocks</h1>
              </div>
              <div className="hidden p-4" id="crypto" role="tabpanel" aria-labelledby="crypto-tab" data-tabs-toggle="#crypto-tab"> {/* Crypto input*/}
                <h1>Crypto</h1>
                <h1>Crypto</h1>
                <h1>Crypto</h1>
                <h1>Crypto</h1>
              </div>
            </div>

        </div>

        <div className="bg-white w-3/4 h-3/4 rounded-xl shadow-lg m-10"> {/* Paper */}
          <div> {/* Value chart */}
            <ResponsiveContainer width={1300} height={500} >
                <LineChart width="100%" height="100%" data={data}>
                  <XAxis dataKey="name" />
                  <YAxis />
                  <Tooltip />
                  <Legend />
                  <Line type="monotone" dataKey="pv" stroke="#8884d8"/>
                  <Line type="monotone" dataKey="uv" stroke="#82ca9d"/>
                </LineChart>
            </ResponsiveContainer>
          </div>      
        </div>

        
           



      </div>
    </div>
  )
}

function StockResult() {

    return (
      <div>

      </div>

    )


}

function CryptoResult() {

  return (
    <div>
      
    </div>

  )

  
}